banAllTradeEnchantmentsByDefault = false
tradeNamespaceBlacklist = []
tradeNamespaceWhitelist = ["minecraft"]
tradeIdBlacklist = []
tradeIdWhitelist = ["minecraft:unbreaking"]
banAllTableEnchantmentsByDefault = false
tableNamespaceBlacklist = []
tableNamespaceWhitelist = ["minecraft"]
tableIdBlacklist = []
tableIdWhitelist = ["minecraft:unbreaking"]

