
[general]
	#When the next EMC mapping occurs write the results to config/ProjectE/pregenerated_emc.json and only ever run the mapping again when that file does not exist, this setting is set to false, or an error occurred parsing that file.
	pregenerate = false
	#Want to take a look at the internals of EMC Calculation? Enable this to write all the conversions and setValue-Commands to config/ProjectE/mappingdump.json
	dumpEverythingToFile = false
	#Log known EMC Exploits. This can not and will not find all possible exploits. This will only find exploits that result in fixed/custom emc values that the algorithm did not overwrite. Exploits that derive from conversions that are unknown to ProjectE will not be found.
	logEMCExploits = true

[CraftingMapper]

	[CraftingMapper.ChippedBotanistWorkbenchMapper]
		#ProjectE-Integration Recipe Mapper for Chipped Botanist Workbench Mapper. Required Mods: [chipped]
		enabled = true

	[CraftingMapper.MysticalAgricultureInfusionMapper]
		#ProjectE-Integration Recipe Mapper for Mystical Agriculture Infusion Mapper. Required Mods: [mysticalagriculture]
		enabled = true

	[CraftingMapper.IndustrialForegoingStoneWorksGenerateMapper]
		#ProjectE-Integration Recipe Mapper for Industrial Foregoing Stone Works Generate Mapper. Required Mods: [industrialforegoing] NOTE: Disabled by default.
		enabled = false

	[CraftingMapper.ChippedAlchemyBenchMapper]
		#ProjectE-Integration Recipe Mapper for Chipped Alchemy Bench Mapper. Required Mods: [chipped]
		enabled = true

	[CraftingMapper.NaturesAuraAltarMapper]
		#ProjectE-Integration Recipe Mapper for Natures Aura Altar Mapper. Required Mods: [naturesaura]
		enabled = true

	[CraftingMapper.ChippedLoomTableMapper]
		#ProjectE-Integration Recipe Mapper for Chipped Loom Table Mapper. Required Mods: [chipped]
		enabled = true

	[CraftingMapper.BloodMagicTartaricForgeMapper]
		#ProjectE-Integration Recipe Mapper for Blood Magic Tartaric Forge Mapper. Required Mods: [bloodmagic]
		enabled = true

	[CraftingMapper.ArsNouveauGlyphMapper]
		#ProjectE-Integration Recipe Mapper for Ars Nouveau Glyph Mapper. Required Mods: [ars_nouveau]
		enabled = true

	[CraftingMapper.Smithing]
		#Maps smithing recipes.
		enabled = true

	[CraftingMapper.ChippedGlassblowerMapper]
		#ProjectE-Integration Recipe Mapper for Chipped Glassblower Mapper. Required Mods: [chipped]
		enabled = true

	[CraftingMapper.BloodMagicAlchemyArrayMapper]
		#ProjectE-Integration Recipe Mapper for Blood Magic Alchemy Array Mapper. Required Mods: [bloodmagic]
		enabled = true

	[CraftingMapper.ChippedCarpentersTableMapper]
		#ProjectE-Integration Recipe Mapper for Chipped Carpenters Table Mapper. Required Mods: [chipped]
		enabled = true

	[CraftingMapper.NaturesAuraTreeRitualMapper]
		#ProjectE-Integration Recipe Mapper for Natures Aura Tree Ritual Mapper. Required Mods: [naturesaura]
		enabled = true

	[CraftingMapper.FallbackRecipeType]
		#Fallback for default handling of recipes that extend ICraftingRecipe, AbstractCookingRecipe, SingleItemRecipe, or SmithingRecipe. This will catch modded extensions of the vanilla recipe classes, and if the VanillaRecipeTypes mapper is disabled, this mapper will still catch the vanilla recipes.
		enabled = true

	[CraftingMapper.VanillaRecipeTypes]
		#Maps the different vanilla recipe types.
		enabled = true

	[CraftingMapper.BloodMagicAlchemyTableMapper]
		#ProjectE-Integration Recipe Mapper for Blood Magic Alchemy Table Mapper. Required Mods: [bloodmagic]
		enabled = true

	[CraftingMapper.IndustrialForegoingDissolutionChamberMapper]
		#ProjectE-Integration Recipe Mapper for Industrial Foregoing Dissolution Chamber Mapper. Required Mods: [industrialforegoing]
		enabled = true

	[CraftingMapper.MysticalAgricultureReprocessorMapper]
		#ProjectE-Integration Recipe Mapper for Mystical Agriculture Reprocessor Mapper. Required Mods: [mysticalagriculture]
		enabled = true

	[CraftingMapper.ArsNouveauCrushMapper]
		#ProjectE-Integration Recipe Mapper for Ars Nouveau Crush Mapper. Required Mods: [ars_nouveau]
		enabled = true

	[CraftingMapper.BloodMagicBloodAltarMapper]
		#ProjectE-Integration Recipe Mapper for Blood Magic Blood Altar Mapper. Required Mods: [bloodmagic]
		enabled = true

	[CraftingMapper.ChippedMechanistWorkbenchMapper]
		#ProjectE-Integration Recipe Mapper for Chipped Mechanist Workbench Mapper. Required Mods: [chipped]
		enabled = true

	[CraftingMapper.ChippedMasonTableMapper]
		#ProjectE-Integration Recipe Mapper for Chipped Mason Table Mapper. Required Mods: [chipped]
		enabled = true

	[CraftingMapper.ArsNouveauImbuementMapper]
		#ProjectE-Integration Recipe Mapper for Ars Nouveau Imbuement Mapper. Required Mods: [ars_nouveau]
		enabled = true

	[CraftingMapper.IndustrialForegoingCrusherMapper]
		#ProjectE-Integration Recipe Mapper for Industrial Foregoing Crusher Mapper. Required Mods: [industrialforegoing]
		enabled = true

	[CraftingMapper.NaturesAuraOfferingMapper]
		#ProjectE-Integration Recipe Mapper for Natures Aura Offering Mapper. Required Mods: [naturesaura]
		enabled = true

	[CraftingMapper.ArsNouveauEnchantingApparatusMapper]
		#ProjectE-Integration Recipe Mapper for Ars Nouveau Enchanting Apparatus Mapper. Required Mods: [ars_nouveau]
		enabled = true

[enabledMappers]
	#Set EMC=0 for everything in the forge:raw_materials tag
	RawOresBlacklistMapper = true
	#Add Conversions for Crafting Recipes gathered from net.minecraft.item.crafting.RecipeManager
	CraftingMapper = true
	#Adds back and forth conversions of objects and their Tag variant. (EMC values assigned to tags will not behave properly if this mapper is disabled)
	TagMapper = true
	#Allows setting EMC values through CraftTweaker. This behaves similarly to if someone used the custom emc file instead.
	CrTCustomEMCMapper = true
	#Add Conversions for Brewing Recipes
	BrewingMapper = true
	#Recipe mapper for custom recipes that don't implement IRecipe
	ProjectEIntegrationRecipeMapper = true
	#Loads json files within datapacks (data/<domain>/pe_custom_conversions/*.json) to add values and conversions
	CustomConversionMapper = true
	#Allows adding custom conversions through CraftTweaker. This behaves similarly to if someone used a custom conversion file instead.
	CrTConversionEMCMapper = true
	#Set EMC=0 for everything in the forge:ores tag
	OresBlacklistMapper = true
	#Add Conversions for all lingering potions to arrow recipes
	TippedArrowMapper = true
	#Add Conversions for all weathered copper variants
	WeatheredCopperMapper = true
	#Uses the `custom_emc.json` File to add EMC values.
	CustomEMCMapper = true
	#Allows other mods to easily set EMC values using the ProjectEAPI
	APICustomEMCMapper = true

