
#Client Configuration
[client]

	[client.visual_options]
		# If plaques should show on the top of the screen.
		on_top = true
		# The distance from the top or bottom of the screen, in pixels.
		#Range: 8 ~ 256
		distance = 16
		# Hide waila/hwyla/jade popups while plaques are showing.
		hide_waila = false
		# If plaques should show for task advancements (normal advancements).
		tasks = true
		# If plaques should show for goal advancements (medium-difficulty advancements).
		goals = true
		# If plaques should show for challenge advancements (high-difficulty advancements).
		challenges = true
		# Text color to use for plaque titles (like "Advancement made!"). Can be entered as an 8-digit hex color code 0xAARRGGBB for convenience.
		#Range: 0 ~ 4294967295
		title_color = 4281541120
		# Text color to use for advancement names on plaques. Can be entered as an 8-digit hex color code 0xAARRGGBB for convenience.
		#Range: 0 ~ 4294967295
		name_color = 4294967295

	[client.duration_options]
		# Duration of the shiny effect fade in for tasks.
		#Range: 0.1 ~ 3.0
		task_effect_fadein = 0.5
		# Duration of the shiny effect fade out for tasks.
		#Range: 0.1 ~ 3.0
		task_effect_fadeout = 1.5
		# Duration of the plaques for tasks (minus the effect fade in/out durations).
		#Range: 2.0 ~ 10.0
		task_duration = 7.0
		# Duration of the shiny effect fade in for goals.
		#Range: 0.1 ~ 3.0
		goal_effect_fadein = 0.5
		# Duration of the shiny effect fade out for goals.
		#Range: 0.1 ~ 3.0
		goal_effect_fadeout = 1.5
		# Duration of the plaques for goals (minus the effect fade in/out durations).
		#Range: 2.0 ~ 10.0
		goal_duration = 7.0
		# Duration of the shiny effect fade in for challenges.
		#Range: 0.1 ~ 3.0
		challenge_effect_fadein = 1.25
		# Duration of the shiny effect fade out for challenges.
		#Range: 0.1 ~ 3.0
		challenge_effect_fadeout = 1.5
		# Duration of the plaques for challenges (minus the effect fade in/out durations).
		#Range: 2.0 ~ 10.0
		challenge_duration = 7.0

	[client.functionality_options]
		# Whitelist of advancements to show plaques for.  Leave empty to display for all.
		whitelist = []
		# If task sounds should be muted.
		mute_tasks = false
		# If goal sounds should be muted.
		mute_goals = false
		# If challenge sounds should be muted.
		mute_challenges = false

