
[miner]
	#The time in ticks between extraction operations performed by the miner.
	#Range: > 0
	cooldown = 100
	#The power efficiency of the miner. Actual mining time per power unit is original value times this. Applies to both internal power generation as well as power supplied externally. Set to 0 to disable power requirement.
	#Range: 0.0 ~ 100.0
	efficiency = 1.0
	#The fuel efficiency of the miner. Total mining time is original burn time times this times `minerEfficiency`. Applies to internal power generation. Set to 0 to disable internal powering.
	#Range: 0.0 ~ 100.0
	fuel_efficiency = 1.0
	#The power efficiency of the miner. Total mining time is original powered time times this times `minerEfficiency`. Applies to power supplied externally. Set to 0 to disable external powering.
	#Range: 0.0 ~ 100.0
	energy_efficiency = 1.0
	#The radius of the incircle of the square area around the miner in which it operates, in blocks. 1 is straight down.
	#Range: 1 ~ 16
	areaRadius = 3
	#The number of layers below the miner in which it operates, in blocks. 1 is just the layer below the miner.
	#Range: 1 ~ 32
	areaLayers = 3

[world]
	#The number of bedrock ore veins to attempt to generate per chunk.
	#Range: 0 ~ 50
	veins_per_chunk = 5
	#Whether to allow players to directly mine bedrock ores. Disabling this will force players to use the bedrock miner.
	player_mining = true

[ui]
	#Whether to only show the floating UI indicating ore yield when sneaking.
	info_only_when_sneaking = true

