
["Elite Tier Options"]
	#
	#Elite Exporter Speed
	#Range: 1.0 ~ 9.0
	eliteExporterSpeed = 2.0
	#
	#Elite Importer Speed
	#Range: 1.0 ~ 9.0
	eliteImporterSpeed = 2.0
	#
	#Elite Constructor Speed
	#Range: 1.0 ~ 20.0
	eliteConstructorSpeed = 2.0
	#
	#Elite Destructor Speed
	#Range: 1.0 ~ 20.0
	eliteDestructorSpeed = 2.0
	#
	#Elite Disk Manipulator Speed
	#Range: 1.0 ~ 20.0
	eliteDiskManipulatorSpeed = 2.0
	#
	#Elite Interface Speed
	#Range: 1.0 ~ 9.0
	eliteInterfaceSpeed = 2.0
	#
	#Elite Requester Max Craft Amount
	#Range: > 1
	eliteRequesterMaxCraftAmount = 2000
	#
	#Elite Energy Cost Multiplier
	#Range: > 0
	eliteEnergyCost = 2

["Ultra Tier Options"]
	#
	#Ultra Exporter Speed
	#Range: 1.0 ~ 9.0
	ultraExporterSpeed = 5.0
	#
	#Ultra Importer Speed
	#Range: 1.0 ~ 9.0
	ultraImporterSpeed = 5.0
	#
	#Ultra Constructor Speed
	#Range: 1.0 ~ 20.0
	ultraConstructorSpeed = 5.0
	#
	#Ultra Destructor Speed
	#Range: 1.0 ~ 20.0
	ultraDestructorSpeed = 5.0
	#
	#Ultra Disk Manipulator Speed
	#Range: 1.0 ~ 20.0
	ultraDiskManipulatorSpeed = 5.0
	#
	#Ultra Interface Speed
	#Range: 1.0 ~ 9.0
	ultraInterfaceSpeed = 5.0
	#
	#Ultra Requester Max Craft Amount
	#Range: > 1
	ultraRequesterMaxCraftAmount = 4000
	#
	#Ultra Energy Cost Multiplier
	#Range: > 0
	ultraEnergyCost = 3

["Mega Tier Options"]
	#
	#Mega Exporter Speed
	#Range: 1.0 ~ 9.0
	megaExporterSpeed = 6.5
	#
	#Mega Importer Speed
	#Range: 1.0 ~ 9.0
	megaImporterSpeed = 6.5
	#
	#Mega Constructor Speed
	#Range: 1.0 ~ 20.0
	megaConstructorSpeed = 6.5
	#
	#Mega Destructor Speed
	#Range: 1.0 ~ 20.0
	megaDestructorSpeed = 6.5
	#
	#Mega Disk Manipulator Speed
	#Range: 1.0 ~ 20.0
	megaDiskManipulatorSpeed = 6.5
	#
	#Mega Interface Speed
	#Range: 1.0 ~ 9.0
	megaInterfaceSpeed = 6.5
	#
	#Mega Requester Max Craft Amount
	#Range: > 1
	megaRequesterMaxCraftAmount = 6000
	#
	#Mega Energy Cost Multiplier
	#Range: > 0
	megaEnergyCost = 4

