
[Mobs]
	#
	# Percent chance that a Husk will wield a Leviathan Blade in the Leviathan.
	# Default: 5
	#Range: 0 ~ 100
	husk_leviathan_blade_chance = 5
	#
	# Determines if Husks will drop sand when spawned in the Leviathan.
	# Default: true
	husks_drop_sand = true
	#
	# Percent chance that a Stray will wear a Frosted Cowl in the Snowy Temple.
	# Default: 5
	#Range: 0 ~ 100
	stray_frosted_cowl_chance = 5
	#
	# Determines if Strays will drop ice when spawned in the Snowy Temple.
	# Default: true
	strays_drop_ice = true
	#
	# Percent chance that a Drowned will wear a Warped Axe in the Warped Garden.
	# Default: 5
	#Range: 0 ~ 100
	drowned_warped_axe_chance = 5
	#
	# Percent chance that a Drowned will hold coral in the Warped Garden.
	# Default: 30
	#Range: 0 ~ 100
	drowned_coral_chance = 30
	#
	# Percent chance that a Skeleton will wield a Soul Cannon in the Soul Prison.
	# Default: 5
	#Range: 0 ~ 100
	skeleton_soul_cannon_chance = 5

[Items]
	#
	# When true, throwable items with loyalty will return if they enter the void.
	# Default: true
	loyalty_returns_from_void = true
	#
	# When true, the fireball from a Soul Cannon enchanted with flame will place fire.
	# Default: true
	soul_cannon_produces_fire = true

["Mod Compat"]

	["Mod Compat".Waystones]
		#
		# Percent chance for a waystone from Waystones to generate on top of the tower
		# Default: 100
		#Range: 0 ~ 100
		tower_waystone_chance = 100

