
[general]
	#If text is enabled, allows it to accept the label dye color
	colored_text = true
	#Item texture resolution. You might want to keep this multiples of 16
	#Range: 8 ~ 512
	texture_resolution = 16

[color_settings]
	#Greyscales then recolors each item. You can customize said colors by overriding 'label_colors.png' with a resourcepack
	recolor_texture = true
	#picks one of the 3 presets for dyes on labels. This simply changes the texture that is used.Requires a resource pack reloadNote that you can always change this manually with a resource pack to control all the colors individually
	#Allowed Values: DEFAULT, PENCIL, PASTEL, FLAT
	color_texture_preset = "PENCIL"
	#Reduce colors of original image before processing. Makes 3d blocks more 2d like by giving them a limited palette
	limit_palette = true
	#Adds an outline to label images
	outline = true

