
#Beam Config
["Loot Beams"]
	#If beams should be colored the same as the Items name (excludes name colors from rarity). This has priority over render_rarity_color.
	render_name_color = true
	#If beams should be colored the same as the Items rarity.
	render_rarity_color = true
	#How close the player has to be to see the beam. (note: ItemEntities stop rendering at 24 blocks, so that is the limit for beams)
	#Range: 0.0 ~ 24.0
	render_distance = 24.0
	#Overrides an item's beam color with hex color. Must follow the specific format: (registryname=hexcolor) Or (#tagname=hexcolor). Example: "minecraft:stone=0xFFFFFF". This also accepts modids.
	color_overrides = []

	#Beam Configuration
	["Loot Beams".Beam]
		#The radius of the Loot Beam.
		#Range: 0.0 ~ 5.0
		beam_radius = 0.55
		#The height of the Loot Beam.
		#Range: 0.0 ~ 10.0
		beam_height = 1.5
		#The Y-offset of the loot beam.
		#Range: -30.0 ~ 30.0
		beam_y_offset = 0.5
		#If the Loot Beam should be shorter for common items.
		common_shorter_beam = true
		#Transparency of the Loot Beam.
		#Range: 0.0 ~ 1.0
		beam_alpha = 0.75
		#The distance from the player the beam should start fading.
		#Range: 0.0 ~ 100.0
		beam_fade_distance = 2.0
		#If the Loot Beam should use a solid texture or the beacon style texture.
		solid_beam = true
		#If the Loot Beam should have a white center.
		white_center = true
		#If the Loot Beam should be glowing.
		glowing_beam = true
		#If the Loot Beam should have a glow effect around the base of the item.
		glow_effect = true
		#The radius of the glow effect.
		#Range: 1.0E-5 ~ 1.0
		glow_effect_radius = 0.5
		#If the glow effect should be animated.
		animate_glow = true
		#If the item must be on the ground to render a beam.
		require_on_ground = true

	#Particle Config
	["Loot Beams".Particles]
		#If particles should appear around the item.
		particles = true
		#The size of the particles.
		#Range: 1.0E-5 ~ 10.0
		particle_size = 0.25
		#The speed of the particles.
		#Range: 1.0E-5 ~ 10.0
		particle_speed = 0.2
		#The radius of the particles.
		#Range: 1.0E-5 ~ 10.0
		particle_radius = 0.1
		#The intensity of the randomness of the particles.
		#Range: 0.0 ~ 1.0
		randomness_intensity = 0.05
		#The amount of particles to spawn per second.
		#Range: 1.0 ~ 20.0
		particle_count = 15.0
		#The lifetime of the particles in ticks.
		#Range: 1 ~ 100
		particle_lifetime = 15
		#If particles should only appear on rare items.
		particle_rare_only = true
		#The direction of the particles on the X axis.
		#Range: -1.0 ~ 1.0
		particle_direction_x = 0.0
		#The direction of the particles on the Y axis.
		#Range: -1.0 ~ 1.0
		particle_direction_y = 1.0
		#The direction of the particles on the Z axis.
		#Range: -1.0 ~ 1.0
		particle_direction_z = 0.0
		#If the particles should spin around the beam.
		spin_around_beam = true
		#If the particles should leave a trail.
		trails = true
		#The chance of a particle leaving a trail.
		#Range: 0.0 ~ 1.0
		trail_chance = 0.5
		#If the particles with a trail should be invisible.
		trail_particles_invisible = true
		#The width of the trail.
		#Range: 1.0E-5 ~ 10.0
		trail_width = 0.2
		#The length of the trail.
		#Range: 1 ~ 200
		trail_length = 30
		#The frequency of the trail. The maximum value this should be is the length. The lower the frequency, the smoother the trail.
		#Range: 1 ~ 200
		trail_frequency = 1

	#Item Config
	["Loot Beams".Items]
		#If items should glow.
		items_glow = false
		#If all Items Loot Beams should be rendered. Has priority over only_equipment and only_rare.
		all_items = false
		#If Loot Beams should only be rendered on items with rarity.
		only_rare = true
		#If Loot Beams should only be rendered on equipment. (Equipment includes: Swords, Tools, Armor, Shields, Bows, Crossbows, Tridents, Arrows, and Fishing Rods)
		only_equipment = true
		#Registry names of items that Loot Beams should render on. Example: "minecraft:stone", "minecraft:iron_ingot", You can also specify modids for a whole mod's items.
		whitelist = []
		#Registry names of items that Loot Beams should NOT render on. This has priority over everything. You can also specify modids for a whole mod's items.
		blacklist = []

	#Item nametags
	["Loot Beams".Nametags]
		#If vanilla tooltips should be rendered on items in world.
		advanced_tooltips = true
		#If tooltips should be rendered in world.
		worldspace_tooltips = true
		#Render nametags as bordered. Set to false for flat nametag with background.
		borders = true
		#If Item nametags should be rendered.
		render_nametags = true
		#If Item nametags should be rendered when looking at items.
		render_nametags_onlook = true
		#If the count of item's should also be shown in the nametag.
		render_stackcount = true
		#How close the player has to look at the item to render the nametag.
		#Range: 0.0 ~ 5.0
		nametag_look_sensitivity = 0.018
		#Transparency of the nametag text.
		#Range: 0.0 ~ 1.0
		nametag_text_alpha = 1.0
		#Transparency of the nametag background/border.
		#Range: 0.0 ~ 1.0
		nametag_background_alpha = 0.5
		#Scale of the nametag.
		#Range: -10.0 ~ 10.0
		nametag_scale = 1.0
		#The Y-offset of the nametag.
		#Range: -30.0 ~ 30.0
		nametag_y_offset = 0.75
		#If a smaller tag should be rendered under with DMCLoot rarities.
		dmcloot_compat_rarity = true
		#Define what the smaller tag should render on. Example: "Exotic", "Ancient". The string supplied has to be the tooltip line below the name. This is really only used for modpacks.
		custom_rarities = []
		#If rarities should ignore color and render as white (This is really only used for modpacks)
		white_rarities = false
		#If vanilla rarities should be rendered.
		vanilla_rarities = true
		#If the player should be crouching to see extended advanced tooltips.
		screen_tooltips_require_crouch = true
		#If the name and rarity should be combined into one tooltip.
		combine_name_and_rarity = false

	#Sounds
	["Loot Beams".Sounds]
		#If sounds should be played when items are dropped up.
		play_sounds = true
		#The volume of the sound.
		#Range: 0.0 ~ 1.0
		sound_volume = 1.0
		#If sounds should play on all items. Has priority over sound_only_equipment and sound_only_rare.
		sound_all_items = false
		#If sounds should only be played on items with rarity.
		sound_only_rare = true
		#If sounds should only be played on equipment. (Equipment includes: Swords, Tools, Armor, Shields, Bows, Crossbows, Tridents, Arrows, and Fishing Rods)
		sound_only_equipment = false
		#Registry names of items that sounds should play on. Example: "minecraft:stone", "minecraft:iron_ingot", You can also specify modids for a whole mod's items.
		sound_whitelist = []
		#Registry names of items that sounds should NOT play on. This has priority over everything. You can also specify modids for a whole mod's items.
		sound_blacklist = []

