
[Client]
	#Multiplier for Caliburn ring speed
	#Range: 0.0 ~ 1.0E8
	POWER_CONSOLIDATION_CALIBURN_RING_SPEED = 1.0
	#Whether to show the circles in the sky
	HEAVENS_CUP_CLIENT_CIRCLE = true
	#How far away Leylines can be seen
	#Range: 0 ~ 100000000
	LEY_RENDER_DISTANCE = 100
	#Toggle for Fae Sounds
	FAE_NOISE = true
	#X value of Mahou value on screen
	#Range: 0 ~ 100000000
	CLIENT_GUI_MAHOU_PLACEMENT_X = 10
	#Y value of Mahou value on screen
	#Range: 0 ~ 100000000
	CLIENT_GUI_MAHOU_PLACEMENT_Y = 20
	#Ring speed for the Mystic Code
	#Range: 0.0 ~ 1.0E8
	MYSTIC_CODE_RING_SPEED = 1.0
	#Spinning speed for boundaries
	#Range: 0.0 ~ 1.0E8
	BOUNDARY_SPEED = 2.0
	#Toggle bleeding potion effect display
	SHOW_BLEEDING = true
	#Mystic Staff Beam Volume Factor
	#Range: 0.0 ~ 10.0
	MYSTIC_STAFF_BEAM_VOLUME_FACTOR = 0.1
	#Added X value to left tab position of Mystic Eyes of Insight
	#Range: -10000 ~ 10000
	INSIGHT_LEFT_X = 0
	#Added Y value to left tab position of Mystic Eyes of Insight
	#Range: -10000 ~ 10000
	INSIGHT_LEFT_Y = 0
	#Added X value to right tab position of Mystic Eyes of Insight
	#Range: -10000 ~ 10000
	INSIGHT_RIGHT_X = 0
	#Added Y value to right tab position of Mystic Eyes of Insight
	#Range: -10000 ~ 10000
	INSIGHT_RIGHT_Y = 0
	#Added X value to bottom tab position of Mystic Eyes of Insight
	#Range: -10000 ~ 10000
	INSIGHT_BOTTOM_X = 0
	#Added Y value to bottom tab position of Mystic Eyes of Insight
	#Range: -10000 ~ 10000
	INSIGHT_BOTTOM_Y = 0
	#Quality of links of the chain, reducing can improve FPS
	#Range: 3 ~ 10000
	CHAIN_QUALITY = 11
	#How loud the chains are
	#Range: 0.0 ~ 10.0
	CHAIN_VOLUME = 0.01
	#Volume control for Caliburn's Smite attack
	#Range: 0.0 ~ 10.0
	SMITE_VOLUME = 1.0
	#Show ability cooldown as a potion effect
	SHOW_MORGAN_CALIBURN_COOLDOWN = false
	#No Shaders
	NO_SHADERS = false
	#Old Circle Render
	OLD_CIRCLE_RENDER = false
	#Old Circle Animation
	OLD_CIRCLE_ANIM = false
	#Show Selected Entity
	SHOW_SELECTED_ENTITY = true
	#Selective Displacement Hold Time
	#Range: 0 ~ 100000
	SELECTIVE_DISPLACEMENT_HOLD_TIME = 5

