
["Instrument GUI"]
	#Instrument GUI keyboard layout for notes. MIMI uses its own layout by default but also supports the layout used by VirtualPiano.net.
	#Allowed Values: MIMI, VPiano
	instrumentKeyboardLayout = "MIMI"

["MIDI Player"]
	#Optional full path to a folder containing MIDI files to be used by the MIDI Player. See guide book for more information.
	playlistFolderPath = ""

["MIDI Input"]
	#What MIDI Input Device should be used (if available)? This can be set from the in-game MIDI Input Device Configuration menu. Changes require a game restart to take affect.
	defaultMidiInputDevice = ""
	#Should MIMI include detailed logs tracking MIDI note input and output?
	enableMidiLogs = false

["MIDI Synth"]
	#Should MIDI notes that are played take into account any blocks between you and the source and muffle the sound accordingly? Note that enabling this may impact performance on lower-end systems.
	rayTraceSound = false
	#Should the built-in midi synthesizer enable Jitter Correction? When enabled note timing will be more accurate but latency will increase.
	synthJitterCorrection = true
	#What baseline latency should the built-in midi synthesizer use (ms) for notes from other players? Smaller values will decrease latency but may cause stutter when playing notes. Very small values may cause notes to fail to play at all.
	#Range: 10 ~ 800
	synthBaselineLatency = 250
	#What baseline latency should the built-in midi synthesizer use (ms) for notes played by you? Smaller values will decrease latency but may cause stutter when playing notes. Very small values may cause notes to fail to play at all.
	#Range: 10 ~ 800
	synthBaselineLocalLatency = 30
	#What sample rate should the built-in midi synthesizer use (hz)? Smaller values may decrease latency but will also decrease quality.
	#Allowed values: [8000,11025,16000,22050,44100,48000,96000]
	synthSampleRate = 44100
	#What bitrate should the built-in midi synthesizer use (bits)? Smaller values may decrease latency but will also decrease quality.
	#Allowed values: [8,16,24,32]
	synthBitRate = 16
	#Optional full path to an SF2 format SoundFont to be used by the MIDI Synthesizer. See project page for more information.
	soundfontPath = ""
	#How many milliseconds should notes from a server buffer before playing locally? Smaller values will decrease latency but may result in stuttering when the server is under heavy load.
	#Allowed values: 0-999
	#Range: 0 ~ 999
	synthBufferMillis = 100

[DEBUG]
	#QX
	#Range: -360 ~ 360
	quatX = 0
	#QY
	#Range: -360 ~ 360
	quatY = 0
	#QX
	#Range: -360 ~ 360
	quatZ = 1
	#QW
	#Range: -360 ~ 360
	quatW = -90
	#XO
	#Range: -99999 ~ 99999
	xOffset = 11
	#YO
	#Range: -99999 ~ 99999
	yOffset = 155
	#XM
	#Range: -1 ~ 1
	xMult = 1
	#YM
	#Range: -1 ~ 1
	yMult = -1

