#Weight for mutant creeper spawns as a percentage of the vanilla creeper spawn weight. Mutants can spawn in every biome and dimension where their vanilla counterparts can be found.
#Range: 0.0 ~ 20.0
mutant_creeper_spawn_weight = 0.05
#Weight for mutant enderman spawns as a percentage of the vanilla enderman spawn weight. Mutants can spawn in every biome and dimension where their vanilla counterparts can be found.
#Range: 0.0 ~ 20.0
mutant_enderman_spawn_weight = 0.05
#Weight for mutant skeleton spawns as a percentage of the vanilla skeleton spawn weight. Mutants can spawn in every biome and dimension where their vanilla counterparts can be found.
#Range: 0.0 ~ 20.0
mutant_skeleton_spawn_weight = 0.05
#Weight for mutant zombie spawns as a percentage of the vanilla zombie spawn weight. Mutants can spawn in every biome and dimension where their vanilla counterparts can be found.
#Range: 0.0 ~ 20.0
mutant_zombie_spawn_weight = 0.05

