
#Personal setting for Chunk Destroyer. These are just default value and you can change them in-game GUI.
[ChunkDestroyerSetting]
	#Whether the machine places initial frame blocks to show working area.
	placeAreaFrame = true
	#If true, quarry works for a chunk and go next chunk when finished.
	chunkByChunk = false
	#If true, quarry starts when it has enough power. If false it starts when you click start button in GUI.
	startImmediately = true

