
#Vanilla Spawn Modifications
[vanilla_spawn_modifications]
	#Disables zombie spawning in deepslate levels. This is done to prevent too many zombies spawning in this area, since the Bouldering Zombie spawns there exclusively
	"Disable deepslate zombie spawning" = true
	#Disables spider spawning in jungle biomes. This is done to prevent too many spiders spawning in this area, since the Jungle Spider spawns there exclusively
	"Disable spider spawning in jungles" = false

#Blocks
[blocks]

	#Jade
	[blocks.jade]
		#If the velocity of projectiles bounced off of a Jade block should be based on its previous velocity instead of a static value. [Warning: Experimental] (default = false)
		"Dynamic ricochet velocity" = false

