
[Sounds]
	#If TRUE, some 'Thermal Series' Blocks will have ambient sounds.
	"Ambient Block Sounds" = true
	#If TRUE, some 'Thermal Series' Mobs will have ambient sounds.
	"Ambient Mob Sounds" = true

[Holidays]
	#If TRUE, some Mobs will have festive hats on certain days. Disabling this will disable it for ALL mobs, including vanilla. May require client restart.
	"Festive Mobs" = true
	#If TRUE, some vanilla Mobs will also have festive hats on certain days. May require client restart.
	"Festive Vanilla Mobs" = true

