
#Here you can set what command gets executed when the final boss spawner is activated.
#Type in the command you want to happen the exact same way as you would in game.
#For example, typing "summon minecraft:skeleton ~ ~ ~" will summon a normal skeleton and typing "summon zombie ~ ~ ~ {Invulnerable:1,HandItems:[{Count:1,id:wooden_sword},{}]}" will summon an invincible zombie that is holding a wooden sword.
#By default, the spawner runs "function twilighttweaks:final_boss_example", which is a mcfunction made for the mod that runs several commands in a row. Mcfunctions are a vanilla feature and you can google how to make one of your own.
#Any command can be ran once, after which the spawner will break itself.
["FINAL BOSS SPAWNER"]
	"The command that the spawner should run: " = "function twilighttweaks:final_boss_example"

#With this mod installed, boss spawners now leave remnants behind (usually, after the actual boss has been killed).
#Additionally, killed hostile mobs in the Twilight Forest dimension have a chance (0.5%) to drop Time powder.
#Using Time powder on boss spawner remnants brings the spawner back, allowing the boss to be fought again.
["BOSS SPAWNER REMNANTS"]
	"The boss spawner feature is enabled: " = true

