
["No Startup Messages"]
	#Enable No Startup Messages module
	noStartupMessagesEnabled = true
	#A list of word sequences that if contained in a message will be stopped.
	noStartupMessagesMessages = ["Railcraft Reborn: A new version", "You are using a beta version of Railcraft Reborn", "You are using a development version of Railcraft Reborn", "This game is using an alpha build of Ender IO"]

