
#Text Engine Config
[text]
	#Allow text renderer to drop shadow, setting to false can improve performance.
	allowShadow = true
	#Fix resolution level at 2. When the GUI scale increases, the resolution level remains.
	#Then GUI scale should be even numbers (2, 4, 6...), based on Minecraft GUI system.
	#If your fonts are not bitmap fonts, then you should keep this setting false.
	fixedResolution = false
	#Control base font size, in GUI scaled pixels. The default and vanilla value is 8.
	#For bitmap fonts, 8 represents a glyph size of 8x or 16x if fixed resolution.
	#This option only applies to TrueType fonts.
	#Range: 6.5 ~ 9.5
	baseFontSize = 8.0
	#Control vertical baseline for vanilla text layout, in GUI scaled pixels.
	#The vanilla default value is 7.
	#Range: 4.0 ~ 10.0
	baselineShift = 7.0
	#Control the text shadow offset for vanilla text rendering, in GUI scaled pixels.
	#Range: 0.20000000298023224 ~ 2.0
	shadowOffset = 0.8
	#Control the text outline offset for vanilla text rendering, in GUI scaled pixels.
	#Range: 0.20000000298023224 ~ 2.0
	outlineOffset = 0.5
	#Set the recycle time of layout cache in seconds, using least recently used algorithm.
	#Range: 2 ~ 15
	cacheLifespan = 6
	#The bidirectional text heuristic algorithm.
	#This will affect which BiDi algorithm to use during text layout.
	#Allowed Values: FIRST_STRONG, ANY_RTL, LTR, RTL, LOCALE, FIRST_STRONG_LTR, FIRST_STRONG_RTL
	textDirection = "FIRST_STRONG"
	#Whether to use Modern UI text rendering pipeline in 3D world.
	#Disabling this means that SDF text and rendering optimization are no longer effective.
	#But text rendering can be compatible with OptiFine Shaders and Iris Shaders.
	#This does not affect text rendering in GUI.
	#This option only applies to TrueType fonts.
	useTextShadersInWorld = true
	#For DEFAULT_FONT and UNIFORM_FONT, should we keep some bitmap providers of them?
	#Ignore All: Equivalent to Force Unicode Font.
	#Keep ASCII: Include minecraft:font/ascii.png, minecraft:font/accented.png, minecraft:font/nonlatin_european.png
	#Keep Other: Include providers in minecraft:font/default.json other than Keep ASCII and Unicode font.
	#Keep All: Include all except Unicode font.
	#Allowed Values: IGNORE_ALL, KEEP_ASCII, KEEP_OTHER, KEEP_ALL
	defaultFontBehavior = "KEEP_ALL"
	#Whether to use text component object as hash key to lookup in layout cache.
	#If you find that Modern UI text rendering is not compatible with some mods,
	#you can disable this option for compatibility, but this will decrease performance a bit.
	#Modern UI will use another cache strategy if this is disabled.
	useComponentCache = true
	#Allow text layout to be computed from non-main threads.
	#Otherwise, block on current thread.
	allowAsyncLayout = true
	#See CSS line-break property, https://developer.mozilla.org/en-US/docs/Web/CSS/line-break
	#Allowed Values: AUTO, LOOSE, NORMAL, STRICT
	lineBreakStyle = "AUTO"
	#Allowed Values: AUTO, PHRASE
	lineBreakWordStyle = "AUTO"
	#When enabled, Modern UI will compute texel density in device-space to determine whether to use SDF text or bilinear sampling.
	#This feature requires GLSL 400 or has no effect.
	#This generally decreases performance but provides better rendering quality.
	#This option only applies to TrueType fonts. May not be compatible with OptiFine.
	smartSDFShaders = true
	#When rendering in 2D, this option allows Modern UI to exactly compute font size in device-space from the current coordinate transform matrix.
	#This provides perfect text rendering for scaling-down texts in vanilla, but may increase GPU memory usage.
	#When disabled, Modern UI will use SDF text rendering if appropriate.
	#This option only applies to TrueType fonts.
	computeDeviceFontSize = true
	#When enabled, Modern UI will use SDF text rendering if appropriate.
	#Otherwise, it uses nearest-neighbor or bilinear sampling based on texel density.
	#This option only applies to TrueType fonts.
	allowSDFTextIn2D = true

